/*
 * Copyright 2010-2023 JetBrains s.r.o. and Kotlin Programming Language contributors.
 * Use of this source code is governed by the Apache 2.0 license that can be found in the license/LICENSE.txt file.
 */

package org.jetbrains.kotlin.test.runners.codegen;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TargetBackend;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link org.jetbrains.kotlin.test.generators.GenerateCompilerTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/testData/debug/inlineScopes")
@TestDataPath("$PROJECT_ROOT")
public class ModularIrLocalVariableBytecodeInlinerTestWithInlineScopesGenerated extends AbstractIrLocalVariableBytecodeInlinerTest {
    @Test
    public void testAllFilesPresentInInlineScopes() throws Exception {
        KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/testData/debug/inlineScopes"), Pattern.compile("^(.+)\\.kt$"), null, TargetBackend.JVM_IR, true);
    }

    @Test
    @TestMetadata("inlineScopes1.kt")
    public void testInlineScopes1() throws Exception {
        runTest("compiler/testData/debug/inlineScopes/inlineScopes1.kt");
    }

    @Test
    @TestMetadata("inlineScopes10.kt")
    public void testInlineScopes10() throws Exception {
        runTest("compiler/testData/debug/inlineScopes/inlineScopes10.kt");
    }

    @Test
    @TestMetadata("inlineScopes2.kt")
    public void testInlineScopes2() throws Exception {
        runTest("compiler/testData/debug/inlineScopes/inlineScopes2.kt");
    }

    @Test
    @TestMetadata("inlineScopes3.kt")
    public void testInlineScopes3() throws Exception {
        runTest("compiler/testData/debug/inlineScopes/inlineScopes3.kt");
    }

    @Test
    @TestMetadata("inlineScopes4.kt")
    public void testInlineScopes4() throws Exception {
        runTest("compiler/testData/debug/inlineScopes/inlineScopes4.kt");
    }

    @Test
    @TestMetadata("inlineScopes5.kt")
    public void testInlineScopes5() throws Exception {
        runTest("compiler/testData/debug/inlineScopes/inlineScopes5.kt");
    }

    @Test
    @TestMetadata("inlineScopes6.kt")
    public void testInlineScopes6() throws Exception {
        runTest("compiler/testData/debug/inlineScopes/inlineScopes6.kt");
    }

    @Test
    @TestMetadata("inlineScopes7.kt")
    public void testInlineScopes7() throws Exception {
        runTest("compiler/testData/debug/inlineScopes/inlineScopes7.kt");
    }

    @Test
    @TestMetadata("inlineScopes8.kt")
    public void testInlineScopes8() throws Exception {
        runTest("compiler/testData/debug/inlineScopes/inlineScopes8.kt");
    }

    @Test
    @TestMetadata("inlineScopes9.kt")
    public void testInlineScopes9() throws Exception {
        runTest("compiler/testData/debug/inlineScopes/inlineScopes9.kt");
    }
}
